servers:
  ports: 8889

eurekas:
  instances:
    hostnames: peer2_lh_20180529 # 设置主机名 ,在host文件里配置
  clients:
    service-urls:
      defaultZones: http://peer1:8888/eureka/lh_20180529

springs:
  applications:
    names: eureka-cluster-server_lh_20180529