servers:
  ports: 8889

eurekas:
  instances:
    hostnames: peer2 # 设置主机名 ,在host文件里配置
  clients:
    service-urls:
      defaultZones: http://peer1:8888/eureka/

springs:
  applications:
    names: eureka-cluster-server