server:
  port: 8889

eureka:
  instance:
    hostname: peer2 # 设置主机名 ,在host文件里配置
  client:
    service-url:
      defaultZone: http://peer1:8888/eureka/

spring:
  application:
    name: eureka-cluster-server