server:
  port: 8083

eureka:
  client:
    registry-fetch-interval-seconds: 30 #表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    service-url:
      defaultZone: http://localhost:7001/eureka/ 
spring:
  application:
    name: cluster-customer-service