server:
  port: 8085 # 服务端口

spring:
  application:
    name: gateway-zuul # 服务名称

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/ # 服务注册中心地址
  instance:
    prefer-ip-address: true

zuul:
  routes: 
    provider-service: /provider/**  
    customer-service: /customer/** 